### ISSUE TITLE
An option when number of keys reaches maxKeys

### ISSUE THREAD

**Issue by popmanhe** [node-cache/node-cache#175] opened 2020-04-17 02:39 UTC
when number of keys reaches maxKeys, there should be an option. Instead of throwing an error, remove the oldest key and add the new key to the store.

Sorry, I am not familiar with coffee script. Otherwise, I'd create a PR instead of creating an issue.

**Comment by erdii** [comment] 2020-05-23 15:41
this is almost a duplicate of #166 

(this will not happen anytime soon: please have a look at https://www.npmjs.com/package/lru-cache)

**Closed by erdii** 2020-05-23 15:41 UTC
