### ISSUE TITLE
Caching takes too long Node v12

### ISSUE THREAD

**Issue by jwerre** [node-cache/node-cache#181] opened 2020-05-29 23:06 UTC
I noticed when caching a Binary image in Node 12 it took upwards of 30 seconds to cache. I switched back to Node 10 and it only took about 3 seconds. I ran the follow test and had these results:

```js

const fs = require('fs').promises;
const NodeCache = require('node-cache');

const imageCache = new NodeCache({
	stdTTL: 3600,
	useClones: false,
});

(async function(){
	
	let img;
	
	try {
		img = await fs.readFile('img.jpg');
	} catch (err) {
		return Promise.reject(err);
	}
	
	console.time('cacheTime');
	imageCache.set( 'img', img );
	console.timeEnd('cacheTime');
	
})()

```

```bash

$ node --version     
v12.16.1

$ node ./img_cache.js
cacheTime: 1726.180ms

$ nvm use 10
Now using node v10.16.0 (npm v6.9.0)

$ node ./img_cache.js
(node:97989) ExperimentalWarning: The fs.promises API is experimental
cacheTime: 399.178ms

```

Any idea what could be happening here?

**Comment by erdii** [comment] 2020-06-01 15:06
Doh! This does not look good :sweat:
Thanks for reporting! :heart: 

Investigating....
---
On my machine:
* node-cache version: 5.1.0

* test image size: 196K
  * Node 10: cacheTime: 13.960ms
  * Node 12: cacheTime: 19.493ms

* test image size: 1,3M
  * Node 10: cacheTime: 90.215ms
  * Node 12: cacheTime: 173.362ms

---

We need to have a deeper look into what is happening here

**Comment by erdii** [comment] 2020-06-03 19:18
This is the culprit in the set operation: [@stats.vsize += @_getValLength( value )](https://github.com/node-cache/node-cache/blob/21a5eb28ab4e95bc3506af0a9a3a8f2392dae1ec/_src/lib/node_cache.coffee#L188)

[_getValLength Implementation](https://github.com/node-cache/node-cache/blob/21a5eb28ab4e95bc3506af0a9a3a8f2392dae1ec/_src/lib/node_cache.coffee#L632)

will investigate further when I have more time

**Comment by sujeshthekkepatt** [comment] 2020-06-04 13:05
Going with `forceString:true` option reduces the time significantly. But stringification comes at its own cost but here as @erdii indicated `_getValLength` drags the code because of the huge array size. As a workaround, you could use `forceString:true` option. Also you could delegate the stringification logic to your application code. thoughts @jwerre @erdii

**Comment by erdii** [comment] 2020-06-05 17:54
Hmh... `Object.keys(anInstanceOfBuffer)` iterates over the buffer and creates an array with indices 😅 
_getValLength assumes the Buffer to be an object and tries to enumerate the keys in an attempt to maintain memory usage stats

[Object.keys( value ).length](https://github.com/node-cache/node-cache/blob/21a5eb28ab4e95bc3506af0a9a3a8f2392dae1ec/_src/lib/node_cache.coffee#L650)

this will fix it:
```
		else if Buffer.isBuffer(value)
			# buffer size in bytes
			value.length
```

**Comment by erdii** [comment] 2020-06-06 13:25
[v5.1.1](https://www.npmjs.com/package/node-cache/v/5.1.1) has been released with the fix!
Thank your for reporting :heart:

Pls reopen if the problem is still there.

On a side note: `cacheTime: 2.937ms` on a raspberry pi 4 is still very slow for storing a reference to a buffer... I'll create an investigation ticket for that

**Closed by erdii** 2020-06-06 13:25 UTC
Labels: pinned
